### ISSUE TITLE
Grand issue #100: user status to the BBS never goes beyond 'logging in'

### ISSUE THREAD

**Issue by dgets** [dgets/DOCshell#100]
While a user is in _dDoc_, the system always reports them as _logging in_ on whatever node.  This should be correctly updated to show at least a little bit of information about what subsystem they are working in.  Actually this should probably, in most areas, be done right alongside _system logging_, which I will admit that I have neglected to keep up to date in most areas for quite some time now.  :(

**Comment by dgets** [comment]
Looks like these are set via `system.node_list[].action`, with the particular bits to toggle being set in _nodedefs.js_ under _/sbbs/exec/load/_.  More fun bit fiddling!

**Comment by dgets** [comment]
Maybe not quite so simple (I'm interested in hearing @gordon-morehouse's commentary on this):

```
23:03 < echicken> NodeAction[system.node_list[n].action]
23:04 < Megaloyeti> johnny on the spot over here
23:04  * Megaloyeti stares at echicken
23:05 < khelair> ack
23:05 < khelair> maybe I will wait until tomorrow
23:06 < khelair> what is this NodeAction[] of which you speak?
23:06 < Megaloyeti> :O
23:06 < khelair> is my dumb showing?  :|
23:06 < echicken> it's defined in nodedefs.js, I believe
23:07 < Megaloyeti> heh nah, I have no idea whats going 
23:07 < echicken> or perhaps it's NodeActions
23:07 < khelair> is it a function or are the square brackets correct?
23:07 < echicken> it's an array
23:07 < khelair> butbutbut isn't .action a bitfield?
23:08  * khelair realizes he has the API
23:08 < khelair> derp
23:08 < echicken> var whatThisPersonIsDoing = 
                  NodeAction[system.node_list[n].action]
23:08 < khelair> oh
23:08 < khelair> getting, not setting
23:08 < khelair> gotcha
23:08 < echicken> there's NodeAction and NodeStatus, which are arrays defined 
                  in nodedefs.js
23:09 < khelair> I'll look more in there and stop being obtuse
23:09 < echicken> system.node_list[n].action and system.node_list[n].status are 
                  indexes into those arrays
```

**Comment by gordon-morehouse** [comment]
My commentary is that Javascript is being abused like 1980s C here, along with everywhere else.

**Comment by dgets** [comment]
That's a good way to put it.

It's funny, the codebase is _good_, and it's got a great feature set...  Clearly the dudes have some serious training.  I wonder why there isn't more work done in the API, at least.  :P

**Comment by dgets** [comment]
This should be fixed, although as more functionality is added there will need to be more hooks put in for proper status updates.  Got a generalized method abstracted out for it now, though; it's nice 'n easy.
