### ISSUE TITLE
Structure in dperroom.js is gibberish

### ISSUE THREAD

**Issue by dgets** [dgets/DOCshell#122]
The objects are in absolute disarray within the hierarchies.  There needs to be serious reorganization done here for it to make any sense.  What a perfect time to catch up on the much outdated documentation on it both inline and on the wiki here!  m(

**Comment by dgets** [comment]
This is good enough for now.  ;)

**Comment by gordon-morehouse** [comment]
Issues like this would be a good opportunity for some pairing with me helicoptering over yr shoulder, I think, and also a starting point for test coverage.

**Comment by dgets** [comment]
Next time I have to do some restructuring I'll call you in to hover, in that case.  I'm actually at a point right now (see issue #126) that could probably use a bit of this.  Just brace yrself for my horrorcode.  I've not been paying much attention to breaking things up into usable pieces for a bit here...  Hence the need for the refactoring.
