### ISSUE TITLE
zap room

### ISSUE THREAD

**Issue by dgets** [dgets/DOCshell#17]
This should be the last of the ones to finish up before this sucker is ready to go alpha on the command shells listing, provided the other shit makes a good pass through.

**Comment by ntwitch** [comment]
Looks like setting scan_cfg = 0 to clear all bits would indicate "don't read this sub", and = 5 to indicate "read all new"

But the bits they set in scan_cfg are spread out.. I'm wondering if they use the other bits for something internal to synchronet.  I may have to toggle them bitwise instead of simply setting the value.  I'll do some testing.

**Comment by dgets** [comment]
There thar be dragons...

Just lettin' you know.  I don't know if you've seen the black & white bug that crept into the shell or not, but holy crap some weird things happen when you start messing with the flags...  Maybe not in _scan_cfg_, but dear sweet jesus the other areas are horror.

**Comment by dgets** [comment]
```
(22:46:20) ntwitch: also if you get the zapped rooms list working, I just need some sort of
isZapped(room_code) and I can integrate it right into my new message loop
```

**Comment by dgets** [comment]
@ntwitch correct me if I'm wrong, in that you're done contributing to this project for now...  I'm going to set this issue as assigned to me at this point.  Then again, all I've seen is that you haven't contributed for some time and I've heard some second-hand stuff that seems to corroborate the fact that you're done on here (at least for the time being).

If I'm mistaken I'll gladly switch this back to being assigned to you.  Otherwise, feel free to jump in.

**Comment by dgets** [comment]
Need to figure out why the correct JSON is being saved for when _Ddoctest_ is logged in, but when the sysop account enters the shell, only ``undefined`` is saved where the JSON is supposed to end up (/sbbs/data/user/userrooms).

Also _userrooms_ needs to have the name changed to go with the convention that I was working with in /sbbs/data/user/.

**Comment by dgets** [comment]
Closing this for more detailed implementation issues now that the code is written but still buggy.
