### ISSUE TITLE
dmbase.js organized illogically

### ISSUE THREAD

**Issue by dgets** [dgets/DOCshell#30]
While scanning through _dmbase.js_ and other files today in an effort to bring the documentation more up-to-date, it came to my attention that during a late night coding session a lot of the methods in that file, specifically under the `msg_base.entry_level` sub-object do not belong there.  This will require a myriad of small changes in different areas of the code, but won't be tough to implement.  Going to try to get this done, as other developers may be coming in to help me polish this up shortly now that the brass tacks are pretty much done.

**Comment by dgets** [comment]
@ntwitch, was this one of the bits that you rewrote for clarity?

**Comment by ntwitch** [comment]
No I've really only touched scanSub and dispMsg in there.  I don't really
like the entry_level object, I think the functions in it should probably be
moved to the msg_base object.

**Comment by dgets** [comment]
Okay, I'll take care of this one.

**Comment by dgets** [comment]
Later on all of this.
