### ISSUE TITLE
After loading debuggers JSON, code falls through in dperuser.js to entering info then breaks

### ISSUE THREAD

**Issue by dgets** [dgets/DOCshell#42]
As the following screenshot shows:

![debug-fallthrough](https://cloud.githubusercontent.com/assets/1900617/6144299/6b4c206a-b18a-11e4-832f-5af523c7f9d9.png)

**Comment by ntwitch** [comment]
The "falling through" is actually in ddoc2.js, line 342.  userRecords.userDataUI.getInfo() is called, and it does what it's coded to.

I think you meant for the call on line 341 to be 

    userRecords.userDataIO.queryDebugSettings(user.name);

Also, while I was looking at queryDebugSettings() I noticed that the call to writeDebugger() is inside the while loop, it would be called every time it loops. I think you meant for it to be called after done == true. Check your curly brackets.

**Comment by dgets** [comment]
Wow, yeah.  I couldn't sleep last night; that was one of the last lines of code that I put in without debugging.  I was exhausted but not yet able to crash out.  Guh.  Horrible, again.  I really need to stop coding when I can barely keep my eyes open.

Pretty sure you're right about the call on 341.  I'll check out the blocking issue, also.  I'm fairly confident you're probably right about it.  Thanks for the heads up, as always.  It's much appreciated.

**Comment by dgets** [comment]
Ayuh, that seems to have fixed it.  Off to the other bugs, all in the name of making it easier to debug the mHdr bug.  Heh.
