### ISSUE TITLE
deleted messages are counted in the "n remaining" read prompt section

### ISSUE THREAD

**Issue by gordon-morehouse** [dgets/DOCshell#53]
Viewing Lobby> on the test system, the room has 1 readable message and a number of deleted messages. The read prompt displays "(11 remaining)" upon reading message #0 (the sole readable message), but there are 0 readable messages remaining.

WHAT I EXPECT
------
Deleted messages should not be counted in the "n remaining" portion of the read prompt.

**Comment by dgets** [comment]
Interesting sidenote: `doMPrompt()` has apparently been completely depreciated for some time.  Commented it out this time around and will completely remove it as soon as I've got this dynamic prompt working with appropriate numbers instead of too many jumps in continuity.

**Comment by ntwitch** [comment]
I don't believe this was "deleted messages", just that the math to calculate remaining messages was using the wrong value for total messages.  This should be fixed as of 93352e1cd8599762e8fa0761b702bca5c1bb90e5.
