### ISSUE TITLE
enter message with line breaks ('^E') not available from room prompt

### ISSUE THREAD

**Issue by gordon-morehouse** [dgets/DOCshell#57]
Feature request. Hitting ^E (enter message with line breaks, or 'Upload message' in DOC parlance) does not appear to be implemented, at least at the room prompt.
 
```
Current Arguments>  

Not so fast . . .
```

**Comment by dgets** [comment]
@gordon-morehouse can you explain what behavior this function is even supposed to have?  I do not believe that I've ever used _^E_ in message entry before in _vDOC_, just _E_ and _e_.  Or am I having some foggy memory here?  Because I thought _E was_ **upload message**...
