### ISSUE TITLE
enter message with line breaks ('^E') explody at read prompt

### ISSUE THREAD

**Issue by gordon-morehouse** [dgets/DOCshell#58]
This is both a feature request and a bug. See #57 for the feature request, which should also work at the read prompt.

WHAT ACTUALLY HAPPENED
------

When I hit ^E at the read prompt, I get told "Invalid choice" for the ^E, **and** for many subsequent random keystrokes (notably, 'i' produces a "Not supported (yet)..."). Hitting 's' will break out of the loop it gets stuck in though.

However, if I hit 'k' at the read prompt, I get "Invalid choice" *and a pause throbber* and then hitting space properly continues to the next message.

```
[Neutron Star> msg #3 (5 remaining)] Read cmd -> Invalid choice
Invalid choice
Invalid choice
Invalid choice
Invalid choice
Not supported (yet)...
Invalid choice
Not supported (yet)...
Invalid choice
Invalid choice
Invalid choice
Stop
End of scanSub() main loop
tmpPtr: 4	inc: 1	fuggit: true
Closed mBase: topegrpneutrons
Ename: scanSubException	Msg: Done with message scan	#: 4
Got topegrpneutrons in user.cursub
Neutron Star>
```

WHAT I EXPECT TO HAPPEN
------

See #57; as for the bug, I'd expect the prompt to simply not respond a la DOC, or alternatively, to say "Invalid choice" and then redisplay, preferably without a pause throbber.

```
[Neutron Star> msg #3 (5 remaining)] Read cmd -> Invalid choice

[Neutron Star> msg #3 (5 remaining)] Read cmd -> 
```

**Comment by dgets** [comment]
Did you have your status bar enabled when you did this?  It sounds to me like this might be more of an issue with the screen length you were using than anything else, at least the pause throbber thing.

As far as the rest of it...  Meh.

**Comment by gordon-morehouse** [comment]
No, and I was using 80x25.

**Comment by dgets** [comment]
You know what this github account is missing?

A good **NO U!**

**Comment by gordon-morehouse** [comment]
The main bug here, you wontfix-ing nerd, is the behavior upon hitting ^E. If that's no longer happening, close it like a beta.

**Comment by dgets** [comment]
**(h)**
