### ISSUE TITLE
Xpress messages not arriving asynchronously until ^P

### ISSUE THREAD

**Issue by dgets** [dgets/DOCshell#72]
I had thought that this was fixed, but apparently the shell does not currently have the _sync_ calls set up in the right areas to be able to receive incoming Xpress messages as they arrive just yet.  This may actually mean that things will be a bit easier, as it will block those messages by default from coming in during message posting.  This does, however, need to be taken care of properly at the prompts, at the very least.

**Comment by dgets** [comment]
```
06:56 < khelair> can anybody tell me offhand if there is a way (not
                 bbs.nodesync()) to enable asynchronous telegrams to come in
                 during a particular routine and/or to shut it back off?
07:00 < echicken> khelair: there are a few things you need to do
07:00 < echicken> so as mentioned, set bbs.sys_status|=SS_MOFF
07:00 < echicken> that turns off the auto-delivery of these messages
07:01 < echicken> then there's ...
07:01 < echicken> I think: system.get_node_message([node number])
07:01 < echicken> so you would call that periodically (in a loop or on a timer)
                  to see if there's a message waiting for this node
07:02 < echicken> and deliver it to the user when it's convenient
```

**Comment by dgets** [comment]
To turn on auto delivery (simple lesson in JavaScript's binary flags toggling):

```
07:08 < khelair> would turning on auto-delivery just be bbs.sys_status=SS_MOFF?
07:09 < khelair> or &=
07:13 < mcmlxxix> &=!SS_MOFF
07:14 < echicken> ^=
```

Many thanks to _echicken_ & _mcmlxxix_ for these words of wisdom.  ;)

**Comment by dgets** [comment]
So yeah, https://github.com/dgets/DOCshell/commit/c85b667cbed376aba14c61f3736b19301f5947ea didn't exactly fix this yet.

**Comment by gordon-morehouse** [comment]
I'm guessing polling and delivery is right out?

**Comment by dgets** [comment]
Actually it's not, I was just going for the simple fix.  I'll try implementing this next...  I just don't really want to have to mess with timers when sitting at a prompt, which is what the flag solution was supposed to fix.

**Comment by dgets** [comment]
This should be fixed now, though I hosed my own user account settings in getting there, I fear.  ;)  Commit https://github.com/dgets/DOCshell/commit/d746718f1da61c784e8de9a1110afe6055737050 should have fixed it.  Let me know if you'd like to help test it at some point, @gordon-morehouse.

**Comment by dgets** [comment]
Well so much for that flag and/or set of operators working.

**Comment by gordon-morehouse** [comment]
Is this related to the skin-crawly explanation of bitwise operators, perhaps? Maybe revisit your diff?

**Comment by ntwitch** [comment]
nah, we just have to rewrite the menus to run as a loop, checking the incoming messages every second or so.  It turns out the flags only decide whether those messages (log on/log off/private message) will automatically print when you run certain bbs commands.

**Comment by dgets** [comment]
A `bbs.nodesync()` (or is it `.node_sync()`) in the body of the loop is all it'll take.

**Comment by dgets** [comment]
'Course, finding out the timeout syntax for `console.getkey()` is taking a little bit.  Better documentation would be helpful; god I feel like a douche repeatedly asking these guys in IRC for such piddly questions.  :P

**Comment by dgets** [comment]
Turns out `console.inkey()` was the answer; hence the poor documentation of that feature that it didn't have.  Ahrhrhr.

**Comment by dgets** [comment]
Whoops didn't do it in the message read prompt yet; going to go implement that and commit it now quick.

**Comment by dgets** [comment]
Done.

**Comment by gordon-morehouse** [comment]
Perhaps you should ask them in IRC for better documentation :)

**Comment by dgets** [comment]
Nope.  Mentioned that a few times and missed out on a few weeks of support for it.  Haven't made that mistake since.

**Comment by gordon-morehouse** [comment]
I suppose you could write it yourself. ;)

**Comment by dgets** [comment]
If the code base were formatted so that I could read it internally, and commented well throughout, I would probably try to do that.  After just looking at a couple of small snippets, though, I utterly refuse.

**Comment by dgets** [comment]
What I have put in their wiki, interestingly enough, has been trimmed down to the point where it is no longer helpful to the layperson trying out _Synchronet_ on _OpenBSD_.  That kind of put a fork in the documentation addition shit right there, too.  Obviously they only want the terse and obtuse.
