### ISSUE TITLE
'?' menu at room prompt not run through pager

### ISSUE THREAD

**Issue by gordon-morehouse** [dgets/DOCshell#73]
the ? menu at the room prompt (short prompt) is longer than my terminal, and there is no --more--

**Comment by dgets** [comment]
This is supposed to be automagically handled by Synchronet.  Obviously it is far beneath what sbbs is worthy of.  I'll implement something manually.

**Comment by dgets** [comment]
This previous comment was an incorrect assumption on my part.  Something got mangled when I was toying with some flags, and shut off the paging.  I'll see what I can do to get that fixed for you.  It's not present in the code any more, so once it's resolved it shouldn't pop up again.
