### ISSUE TITLE
'x' at read prompt does not allow eXpress message entry

### ISSUE THREAD

**Issue by gordon-morehouse** [dgets/DOCshell#75]
```
[Neutron Star> msg #2 (6 remaining)] Read cmd -> Not supported (yet)...
```

Since code exists, maybe this one is easy.

**Comment by dgets** [comment]
Yeah this'll be simple.

**Comment by dgets** [comment]
Yeah this one should be very simple.  I'm really surprised that it wasn't already in there, actually.  Thought maybe this was something where a commit had broken it but nope, it was just never implemented...

**Comment by dgets** [comment]
Okay, so the prompt isn't brought back up like it should afterwards, but technically this bug is completed.  ;)
