### ISSUE TITLE
Session timeout will anger DOC users used to weeks-long sessions

### ISSUE THREAD

**Issue by gordon-morehouse** [dgets/DOCshell#79]
```
Time's up.
Connection closed by foreign host.
```

nahhhdood. Up the session timeout to 24-48 hours to match existing/prior DOC BBSes (which actually had a comment in the source Just Don't increase it beyond 100 hours, heh)

**Comment by dgets** [comment]
This is an issue dependent upon the security level of the user.  I'll have to decide on whether or not to create a custom level for ddoc users (and have the code verify that they are switched to it), or else just have the code make sure that the timeout is not set as such.

Funny that that happened to you.  Your access level shouldn't allow that.  I'll have to check your settings and brush up on my knowledge of them a little better, too.

**Comment by dgets** [comment]
I believe I've fixed this, unless `|=` and `&=` are working unintuitively in the `user.security.exemptions` field as they were in the other flag areas.  We'll see upon the next longstanding _ddoc_ user session, I guess.

**Comment by dgets** [comment]
Actually maybe it should be the _T_ flag:

```
08:00 < art> khelair, if you're referring to "don't log user out after inactivity
             time period" --> exemption H. If you're referring to "no time
             limits" ---> T
```

We'll see how it goes...

**Comment by dgets** [comment]
Okay so here's the gold bits on the bitwise operators:

```
11:56 < echicken> You probably don't want &= there
11:56 < echicken> https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators
12:03 < echicken> khelair: if you're using &= in the hopes of unsetting a 
                  particular bit, try ^= instead
12:31 < Deuce> echicken, &=~ is the normal way to unset something.
12:32 < Deuce> FLAGS&=~UNSET_THIS
12:32 < Deuce> ^= toggles it.
```

**Comment by dgets** [comment]
Fixed, not toggling, finally as of: https://github.com/dgets/DOCshell/commit/6d075a57566ee6fdc207de770304fa15ea2fa263

**Comment by gordon-morehouse** [comment]
That IRC paste makes my skin crawl. And I'm quite familiar with bit-fiddling. Looks like they've ripped it out now (?) but some of my finest PHP code was generating something that looked like cw2Zjm9Bfd that encoded every possible search param on the TFAW online store - which is still running PHP, I notice.
