### ISSUE TITLE
add 'newcomer' tag to project

### ISSUE THREAD

**Issue by gordon-morehouse** [dgets/DOCshell#80]
A lot of people are adding a 'newcomer' tag to their projects, which translates as "someone not familiar with the source might be able to fix this bug fairly easily." This would be useful here!

**Comment by dgets** [comment]
Ereh are you talking about **labels** for issues or something different?  If different I may have to have you _corrrrrrrrrrrrrrrrect_ me in the proper ways.

No doubt if the old DOC users stumble across this comment slash will be written from it.

**Comment by gordon-morehouse** [comment]
ew, this is my IRLname account.

I mean, not ew, what I meant was, sorry pardner, but I don't swing that way.

And yeah, label, tag, wtfever.

**Comment by dgets** [comment]
Any ideas on how to add a tag?  Derp.

**Comment by gordon-morehouse** [comment]
https://guides.github.com/features/issues/#filtering

the zen of the gear has taken over the web, just like the zen of the triangle has taken over OS X.

**Comment by dgets** [comment]
Except like adding a new one doesn't work and stuff.

**Comment by dgets** [comment]
@gordon-morehouse:
Yeah, I just reviewed that entire link that you posted again, and I'm still not seeing anything about how to add a new label.  If you can find something else, I'd love to do this, but I'm not having any luck finding documentation on how to do that at all.  I'll post on IRC today, but if you've got anything before I get info back on that it'd be much appreciated....

**Comment by dgets** [comment]
@gordon-morehouse Let me know if you find out anything on how to do this.
