### ISSUE TITLE
Mail subsystem is implemented only for 'y'elling to SysOp

### ISSUE THREAD

**Issue by dgets** [dgets/DOCshell#99]
Obviously, 'j'ump to 'mail' needs to be handled here with some modularized code from _dmbase.js_.  Shouldn't be much beyond configuring getting a little more information from the user, using the same routines, and sending them with the correct headers.

**Comment by dgets** [comment]
Starting work on this by modularizing addMsg() a little bit more.

**Comment by dgets** [comment]
Make that a lot more.  Anyway, I believe the routines are good to go; they're not working perfectly in the message bases any more, but I believe that's because I threaded together the different objects incorrectly.  Putting together a **Mail>** room/sub should be much easier now.

**Comment by dgets** [comment]
Ugh just found out this, when trying to find out why the message scan pointers weren't working for the 'mail' sub (thanks to **Nightfox** from _DOVE-Net_ for this information):

_I've been working on a new message reader, and I've found that the msg_area, and it seems to me that the "mail" is a special case in that the msg_area.grp, msg_ara.sub, etc. arrays don't seem to be defined for the "mail" area.  Those arrays seem to be only defined for the sub-boards.  So, I don't think there is a last-read pointer, etc. defined for the "mail" area.  If you want to find the last read message for a user in the "mail" area, you'll need to go through all messages in the "mail" area, look for the ones written to the current logged-in user, and look at the 'attr' field in the message headers and find the last one that has the MSG_READ attribute set.  For example, something like this:_

```
var msgbase = new MsgBase("mail");
if (msgbase.is_open)
{
   var lastReadMsgIdx = 0;
   for (var i = 0; i < msgbase.total_msgs; ++i)
   {
      var msgHdr = msgbase.get_msg_header(true, i, true);
      if ((msgHdr.to_ext == user.number) && ((msgHdr.attr & MSG_READ) ==
MSG_READ))
         lastReadMsgIdx = i;
   }
   msgbase.close();
}
else
   console.print("Uh-oh, failed to open personal mail!\r\n\1p");
```

**Comment by gordon-morehouse** [comment]
Wow, that is remarkably sad.

**Comment by dgets** [comment]
Well, I understand the logic behind it, to an extent...  You remember the differences between how oldschool, full featured, BBS systems processed mail and how DOCish systems do, I'm sure...  The usual in the full BBS world is that you can select a mail message, read it, and it won't affect the status of the others.  So you can read them out of order without affecting the scan pointers, or whatever...  Still, this is not how I would have done it.  You'd think that such similar functionality would be handled with more modular work.  I wonder how many wheels are recreated in there.  Heh.

Really, though, the addition of that pointer wouldn't have any effect on the default shell so long as the code behind that mail subsystem weren't changed.  Why not throw that damn pointer in?

The lack of a scan_ptr seems like a ridiculous oversight and/or pigeonholing into only working with the one shell, despite the flexibility for anyone to code a shell.  Why wouldn't you have it there, since you're using the same objects to work with it?  Especially as JavaScript fails so transparently in such cases?  Guh.

**Comment by gordon-morehouse** [comment]
Yeah, DOC's Mail> was actually just a specific room number (0 or 2 or something) that had some escapes and special handling in the code, so they hacked it a different way I guess.

**Comment by dgets** [comment]
Got a good portion of the UX issues and logic debugged this morning.  Object references are now carried out the right way, but not saving the new (even _blank_ new object) JSON information in the user file.  So this will need to be debugged upon return from work today, hopefully this won't have to wait until tomorrow morning's bright coding light time.

**Comment by dgets** [comment]
I do believe I'm going to try rewriting the majority of ``readMail()`` today to see if I can't get this a little more functional.  It's looking like spaghetticode right now.

**Comment by dgets** [comment]
**Mail>** is, indeed, now properly displaying.  There are still issues with the navigation flow control for reading the different messages for the user, or at least ending a read.  This should be a lot easier to work out now, though.

The real question is why isn't this working when I call it with all of the appropriate options?  I had to finally break down & cut 'n paste the contents of the displaying routine to do that straight out of the _Mail>_ flow control loop and now it works.  :P

**Comment by dgets** [comment]
'End of Messages' bug now fixed so that things are properly detected.  It's not waiting for the prompt before dumping back out to _Lobby>_ right now, so that still needs to be fixed, but all in all reading messages is good.

Need to work on sending message next; once that's finished I'll close this generalized issues and just let more specific ones for the bugs take over.

**Comment by dgets** [comment]
Actually, as _Mail>_ is not now solely implemented for _Yell_, I'm going to close this issue so that I can start using more specific ones immediately.  Good riddance.
